config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "about" => "welcome#about"
  get "final_project" => "welcome#final_project"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end


def about
end 

def final_project
end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div>
		<%= link_to "Home", root_path %>
		<%= link_to "About Me", about_path %>
		<%= link_to "Final Project", final_project_path %>


	</div>

<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About page ! </h1>


<ul>
	<li> Site created by Nicholas Costa </li>
	<li> Email: travelsbybike@gmail.com </li>
	<li> Birthdate: Sept 23 </li>
	<li> Hometown: Spring Hill, TN </li>
	<li> My Favorite Food: Seafood </li>
	<li> My Favorite Movie: Freddy Got Fingered </li>
	<li> My Favorite Song: Pig  My Favorite Band: Dave Matthews Band </li>
</ul>

app/views/welcome/final_project.html.erb
<h1> My Final Project Page </h1>


<ol>
<li> Ok Commuter API  - This is the idea I will be working on but if time allows </li>
<li> SoundGraffiti Website - Accesses the SoundCloud API and displays location based sounds </li>
<li> Third idea   </li> 
</ol>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>

Welcome to my first Rails site.  